### DO NOT EDIT THIS FILE

# edits should not be necessary. Any changes you need to make may be done in
# config.mk 

include ./config.mk


### constants

#### Directories 
SRC_DIR=src
TEST_DIR=tests

#### exec
EXEC=$(EXEC_DIR)/$(EXEC_NAME)

#### Files
HEADERS=$(wildcard $(SRC_DIR)/*.hpp)

SOURCES=$(SRC_DIR)/computation_measurements.cpp $(SRC_DIR)/fhv_main.cpp \
$(SRC_DIR)/saturation_diagram.cpp
OBJS=$(SOURCES:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)

SOURCES_SHARED_LIB=$(SRC_DIR)/performance_monitor.cpp
OBJS_SHARED_LIB=$(SOURCES_SHARED_LIB:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)

ASM=$(SOURCES:$(SRC_DIR)/%.cpp=$(ASM_DIR)/%.s) \
$(SOURCES_SHARED_LIB:$(SRC_DIR)/%.cpp=$(ASM_DIR)/%.s)

#### perfgroup things
SYSTEM_PERFGROUPS_DIR=$(LIKWID_PREFIX)/share/likwid/
PERFGROUPS_ROOT_DIR_NAME=perfgroups
PERFGROUPS_DIRS=$(shell find $(wildcard $(PERFGROUPS_ROOT_DIR_NAME)/*) -type d)

#### perfmon lib
PERFMON_LIB=$(BUILT_LIB_DIR)/$(PERFMON_LIB_NAME)


#### Flags for compilation proper

LIKWID_INC_DIR=-I$(LIKWID_PREFIX)/include
FHV_INC_DIRS=-I./$(SRC_DIR)
PANGOCAIRO_INC_DIRS=$(shell pkg-config --cflags pangocairo)
# combine everything above
INC_DIRS=$(LIKWID_INC_DIR) $(FHV_INC_DIRS) $(PANGOCAIRO_INC_DIRS)

# used as parts of constants below
CXXFLAGS_BASE=$(INC_DIRS) -std=c++14 -fopenmp -DLIKWID_PERFMON
CXXFLAGS_DEBUG=$(CXXFLAGS_BASE) -Wall -g 

# used in actual compilation
CXXFLAGS=$(CXXFLAGS_BASE) $(ADDITIONAL_COMPILER_FLAGS)
CXXFLAGS_SHARED_LIB=$(CXXFLAGS_BASE) $(ADDITIONAL_COMPILER_FLAGS) -fpic
CXXASSEMBLYFLAGS=$(CXXFLAGS_BASE) -S -g -fverbose-asm


#### Flags for linking
LIKWID_LIB_DIR=-L$(LIKWID_PREFIX)/lib
PERFMON_LIB_DIR=-L$(BUILT_LIB_DIR)
# combine everything above
LIB_DIRS=$(LIKWID_LIB_DIR) $(PERFMON_LIB_DIR)

LIKWID_LIB_FLAG=-llikwid
PERFMON_LIB_FLAG=-l$(PERFMON_LIB_NAME_SHORT)
BOOST_PO_LIB_FLAG=-lboost_program_options
PANGOCAIRO_LIB_FLAG=$(shell pkg-config --libs pangocairo)
OPENMP_LIB_FLAG=-fopenmp
# combine everything above
LIBS=$(LIKWID_LIB_FLAG) $(PERFMON_LIB_FLAG) $(BOOST_PO_LIB_FLAG) \
$(PANGOCAIRO_LIB_FLAG) $(OPENMP_LIB_FLAG)

LDFLAGS=$(LIB_DIRS) $(ADDITIONAL_LINKER_FLAGS) $(LIBS)
# TODO: test if we need -fopenmp during linking
# LDFLAGS=$(LIB_DIRS) $(LIBS) -fopenmp

LDFLAGS_SHARED_LIB=$(ADDITIONAL_LINKER_FLAGS) -shared


#### meta-rules: These are the rules designed for the user to call

all: build

build: $(EXEC) $(PERFMON_LIB)

install: $(EXEC) $(PERFMON_LIB)
	@cp $(EXEC) $(FHV_PERFMON_PREFIX)/bin/$(EXEC_NAME);
	@cp $(PERFMON_LIB) $(FHV_PERFMON_PREFIX)/lib/$(PERFMON_LIB_NAME);

tests: run-tests/thread_migration bin/tests/likwid_minimal-run \
run-tests/benchmark-likwid-vs-manual bin/tests/fhv_minimal-run

build-examples: 
	@cd examples/polynomial_expansion; make;
	@cd examples/convolution; make;

assembly: $(ASM)

fhv: $(EXEC)
	$(EXEC)

perfgroups: $(PERFGROUPS_DIRS)

clean:
	rm -rf $(wildcard $(BUILD_DIR)/*)

#### utility rules
# TODO: what do we want this rule to do?
debug:
	@echo "sources:              $(SOURCES)";
	@echo "objects:              $(OBJS)";
	@echo "sources (shared lib): $(SOURCES_SHARED_LIB)";
	@echo "objs (shared lib):    $(OBJS_SHARED_LIB)";
	@echo "exec:                 $(EXEC)";
	@echo "asm:                  $(ASM)"; 
debug: LDFLAGS += -Q --help=target
# debug: clean build


## Inner workings: this is the end of meta-rules


### COMPILATION PROPER
$(OBJS): $(SOURCES) $(HEADERS) | $(OBJ_DIR)

define compile-command
$(CXX) $(CXXFLAGS) -c $< -o $@
endef

## compilation of sources
$(OBJ_DIR)/computation_measurements.o: $(SRC_DIR)/computation_measurements.cpp
	$(compile-command)

$(OBJ_DIR)/saturation_diagram.o: $(SRC_DIR)/saturation_diagram.cpp
	$(compile-command)

# main file
$(OBJ_DIR)/fhv_main.o: $(SRC_DIR)/fhv_main.cpp
	$(compile-command)

## compilation of performance_monitor lib
$(OBJS_SHARED_LIB): $(SOURCES_SHARED_LIB) $(HEADERS) | $(OBJ_DIR)

define compile-command-shared-lib
$(CXX) $(CXXFLAGS_SHARED_LIB) -c $< -o $@
endef

$(OBJ_DIR)/performance_monitor.o: $(SRC_DIR)/performance_monitor.cpp
	$(compile-command-shared-lib)


### LINKING

## linking perfmon shared lib
$(PERFMON_LIB): $(OBJS_SHARED_LIB) | $(BUILT_LIB_DIR)
	$(CXX) $^ $(LDFLAGS_SHARED_LIB) -o $@

## linking executable
$(EXEC): $(OBJS) $(PERFMON_LIB) | $(EXEC_DIR)
	$(CXX) $(OBJS) $(LDFLAGS) -o $@

### CREATING ASSEMBLY
$(ASM): | $(ASM_DIR)

define asm-command
$(CXX) $(CXXFLAGS) $(CXXASSEMBLYFLAGS) $< -o $@
endef

$(ASM_DIR)/%.s: $(SRC_DIR)/%.cpp 
	$(asm-command)

$(ASM_DIR)/%.s: $(TEST_DIR)/%.cpp
	$(asm-command)

$(ASM_DIR)/%.s: $(TEST_DIR)/%.c
	$(asm-command)

### rules to create directories
define mkdir-command
mkdir -p $@
endef

$(BUILT_LIB_DIR):
	$(mkdir-command)

$(EXEC_DIR):
	$(mkdir-command)

$(TEST_EXEC_DIR):
	$(mkdir-command)

$(OBJ_DIR):
	$(mkdir-command)

$(ASM_DIR):
	$(mkdir-command)

### rules to copy perfgroups
.PHONY: $(PERFGROUPS_DIRS)

define copy-perfgroups-command
sudo cp $(wildcard $@/*) $(SYSTEM_PERFGROUPS_DIR)$@/
endef

$(PERFGROUPS_DIRS):
	@echo sudo permission needed to copy to system directory. This will override
	@echo previously-copied groups but not groups shipped with likwid. The full
	@echo command to be issued is printed below:
	@echo
	@echo "$(copy-perfgroups-command)"
	@$(copy-perfgroups-command)

### Test rules
#TODO: make this more DRY...
#TODO: update so they have "-run" suffix instead of "run-" prefix
bin/tests/benchmark-likwid-vs-manual: $(OBJ_DIR)/benchmark-likwid-vs-manual.o $(LIB_OBJS) | $(TEST_EXEC_DIR)
	$(ld-command)

run-tests/benchmark-likwid-vs-manual: bin/tests/benchmark-likwid-vs-manual 
	LD_LIBRARY_PATH=$(LIKWID_PREFIX)/lib bin/tests/benchmark-likwid-vs-manual

bin/tests/thread_migration: $(OBJ_DIR)/thread_migration.o $(LIB_OBJS)  | $(TEST_EXEC_DIR)
	$(ld-command)

run-tests/thread_migration: bin/tests/thread_migration
	LD_LIBRARY_PATH=$(LIKWID_PREFIX)/lib bin/tests/thread_migration 0; \
	# bin/tests/thread_migration 1; \
	bin/tests/thread_migration 2;

bin/tests/likwid_minimal: $(TEST_DIR)/likwid_minimal.c | $(TEST_EXEC_DIR)
	gcc tests/likwid_minimal.c -I$(LIKWID_PREFIX)/include -L$(LIKWID_PREFIX)/lib -march=native -mtune=native -fopenmp -llikwid -o $@

bin/tests/likwid_minimal-run: bin/tests/likwid_minimal
	LD_LIBRARY_PATH=$(LIKWID_PREFIX)/lib bin/tests/likwid_minimal

bin/tests/likwid_minimal-run-with-cli: bin/tests/likwid_minimal
	# if this rule is to be used, the setenv stuff in likwid_minimal.c should be
	# commented out 
	LD_LIBRARY_PATH=$(LIKWID_PREFIX)/lib $(LIKWID_PREFIX)/bin/likwid-perfctr -C S0:0-3 -g MEM -g L2 -g L3 -g FLOPS_SP -g FLOPS_DP -g PORT_USAGE1 -g PORT_USAGE2 -g PORT_USAGE3 -M 1 -m bin/tests/likwid_minimal

run-tests/port-counter-cli: bin/tests/likwid_minimal
	# if this rule is to be used, the setenv stuff in likwid_minimal.c should be
	# commented out 
	LD_LIBRARY_PATH=$(LIKWID_PREFIX)/lib $(LIKWID_PREFIX)/bin/likwid-perfctr -C S0:0-3 -g PORT_USAGE1 -g PORT_USAGE2 -g PORT_USAGE3 -g PORT_USAGE_TEST -M 1 -m bin/tests/likwid_minimal

bin/tests/fhv_minimal: $(OBJ_DIR)/fhv_minimal.o $(LIB_OBJS) | $(TEST_EXEC_DIR)
	$(ld-command)

bin/tests/fhv_minimal-run: bin/tests/fhv_minimal
	LD_LIBRARY_PATH=$(LIKWID_PREFIX)/lib bin/tests/fhv_minimal
